### ISSUE TITLE
consider allowing formatting options

### ISSUE THREAD

**Issue by xjamundx** [krakenjs/makara-amdify#5]
``` js
{
    format: "amd", // cjs, global
    globalVar: "__MAKARA_TEMPLATES__"  // in the case of global
}
```

**Comment by aredridel** [comment]
This module is specifically AMD.

There's `makara-browserify` for cjs modules, though making a webpack plugin might make sense for your case.

Configurability has an ongoing cost. If a module only does one thing, then it's a name for that configuration and it makes it a lot easier to talk about. It's no longer "using browserify with foo bar baz and grunt-foo with blorch set to blingle", it's "I'm using makara-amdify". ;-)

**Comment by xjamundx** [comment]
`makara-browserify` took 20s longer to compile, so I'm using this one ;-)

We're using webpack, so we can support either....a webpack plugin sounds fancy/nice. I'll look into that.

Let me show you what we're doing and maybe you can help us come up with a better way. :)

Thanks!

**Comment by grawk** [comment]
@xjamundx is it ok if we close this?

**Comment by xjamundx** [comment]
haha i've re-written this code a few times now :) should probably open source it at this point
